class Color:
    def __init__(self, *args, **kwargs): ...

    def bold(self) -> 'Color': ...
    def dim(self) -> 'Color': ...
    def italic(self) -> 'Color': ...
    def underline(self) -> 'Color': ...
    def blink(self) -> 'Color': ...
    def blink_fast(self) -> 'Color': ...
    def reverse(self) -> 'Color': ...
    def hidden(self) -> 'Color': ...
    def through(self) -> 'Color': ...

    # fg
    def black(self) -> 'Color': ...
    def red(self) -> 'Color': ...
    def green(self) -> 'Color': ...
    def yellow(self) -> 'Color': ...
    def blue(self) -> 'Color': ...
    def magenta(self) -> 'Color': ...
    def cyan(self) -> 'Color': ...
    def white(self) -> 'Color': ...
    def bright_black(self) -> 'Color': ...
    def bright_red(self) -> 'Color': ...
    def bright_green(self) -> 'Color': ...
    def bright_yellow(self) -> 'Color': ...
    def bright_blue(self) -> 'Color': ...
    def bright_magenta(self) -> 'Color': ...
    def bright_cyan(self) -> 'Color': ...
    def bright_white(self) -> 'Color': ...

    # bg
    def bg_black(self) -> 'Color': ...
    def bg_red(self) -> 'Color': ...
    def bg_green(self) -> 'Color': ...
    def bg_yellow(self) -> 'Color': ...
    def bg_blue(self) -> 'Color': ...
    def bg_magenta(self) -> 'Color': ...
    def bg_cyan(self) -> 'Color': ...
    def bg_white(self) -> 'Color': ...
    def bg_bright_black(self) -> 'Color': ...
    def bg_bright_red(self) -> 'Color': ...
    def bg_bright_green(self) -> 'Color': ...
    def bg_bright_yellow(self) -> 'Color': ...
    def bg_bright_blue(self) -> 'Color': ...
    def bg_bright_magenta(self) -> 'Color': ...
    def bg_bright_cyan(self) -> 'Color': ...
    def bg_bright_white(self) -> 'Color': ...
